# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . ./
RUN npm run build

# Set the default command to start the MCP server
CMD ["node", "dist/index.js"]
